# Generated by Django 2.2.7 on 2019-12-02 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(default='', max_length=50)),
                ('cl_cycle', models.CharField(default='', max_length=50)),
                ('cl_created_year', models.DateTimeField(default=django.utils.timezone.now, verbose_name='cl_year')),
            ],
            options={
                'ordering': ('cl_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('st_name',)},
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='st_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='st_createdDate'),
        ),
        migrations.AddField(
            model_name='student',
            name='st_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='st_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='st_password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='st_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='st_school_year',
            field=models.CharField(default='', max_length=50, verbose_name='st_scYear'),
        ),
        migrations.AddField(
            model_name='student',
            name='st_username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Student_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stc_year', models.CharField(default='', max_length=50, verbose_name='stc_year')),
                ('stc_class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Classe')),
                ('stc_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Student')),
            ],
            options={
                'ordering': ('stc_year',),
            },
        ),
    ]
